/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.odu.cs.cs350;

import org.junit.Test;
import static org.junit.Assert.*;

public class DriverTest {
    @Test public void appHasAGreeting() {
        Driver classUnderTest = new Driver();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
