/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.odu.cs.cs350;
import java.util.Arrays;
import java.io.*;

public class Driver {
    public static void main(String[] args) throws IOException {
    // // Enter data using BufferReader
    BufferedReader reader = new BufferedReader(
                            new InputStreamReader(System.in));

    // Reading data using readLine
    String name = reader.readLine();

    // Printing the read line
    System.out.println(name);

    }
}
