/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.odu.cs.cs350;

import java.util.Arrays;
import java.io.*;
import java.lang.StringBuilder;

public class Driver {
    private String block;

    public static void main(String[] args) throws IOException {
        // // Enter data using BufferReader
        BufferedReader reader = new BufferedReader(
                new InputStreamReader(System.in));

        // Reading data using readLine
        String name = reader.readLine();

        // Printing the read line
        System.out.println(name);

    }

    public void displayMarkedUpBlock() {

        // String markedUp = Extractor.markPersonalNames(block);
        // System.out.println(markedUp);
    }

    // might want to think about using a scanner here so we can read one word at a
    // time
    public static String readBlock(BufferedReader reader) {

        StringBuilder newBlock = new StringBuilder();
        String word;

        /*
         * while ((word = reader.next()) != "</NER>"){
         * 
         * newBlock.append(word);
         * }
         */

        return newBlock.toString();

    }

}
